ARG fedora_version=34
FROM localhost/base:${fedora_version}

LABEL com.github.containers.toolbox="true" \
      usage="This image is meant to be used by toolbox -i <image-name> <container-name>" \
      summary="Image for development of Anaconda and related projects" \
      maintainer="Jiri Konecny <DragonLich@psmail.xyz>"

RUN dnf copr enable -y atim/starship && \
    dnf install -y \
    starship \
    glibc-langpack-cs \
    git \
    make \
    vim \
    packit \
    tmt \
    tig \
    glade \
    python3-pylint \
    python3-sphinx \
    python3-sphinx_rtd_theme \
    # tooling requirements
    ansible \
    # required for translation check in Anaconda
    python3-polib \
    python3-wheel \
    # required for autotools and development
    npm \
    # pep8 checker
    python3-pycodestyle \
    python3-coverage \
    ShellCheck \
    # anaconda-webui dependencies
    'dnf-command(builddep)' \
    adobe-source-code-pro-fonts \
    byobu \
    chromedriver \
    chromium-headless \
    curl \
    firefox \
    gcc-c++ \
    genisoimage \
    gnupg \
    google-noto-cjk-fonts-common \
    intltool \
    jq \
    lcov \
    libXt \
    libappstream-glib \
    libvirt-client \
    libvirt-daemon-driver-qemu \
    libvirt-daemon-driver-storage-core \
    libvirt-python3 \
    nc \
    net-tools \
    nodejs-devel \
    npm \
    pigz \
    podman-remote \
    procps-ng \
    psmisc \
    python3 \
    python3-aiohttp+speedups \
    python3-aioresponses \
    python3-build \
    python3-flake8 \
    python3-mypy \
    python3-pcp \
    python3-pika \
    python3-pillow \
    python3-pip \
    python3-pytest \
    python3-pytest-asyncio \
    python3-pytest-timeout \
    python3-pyyaml \
    python3-types-pyyaml \
    python3-vulture \
    python3-wheel \
    qemu-kvm-core \
    rpm-build \
    rpmdevtools \
    rsync \
    ruff \
    socat \
    strace \
    tar \
    valgrind \
    vim-enhanced \
    virt-install \
    && \
    dnf builddep -y anaconda

# Enable to run podman from inner of the container
RUN ln -fs /usr/bin/distrobox-host-exec /usr/bin/podman
