ARG fedora_version=34
FROM localhost/base:${fedora_version}

LABEL com.github.containers.toolbox="true" \
      usage="This image is meant to be used by toolbox -i <image-name> <container-name>" \
      summary="Image for development of Anaconda and related projects" \
      maintainer="Jiri Konecny <DragonLich@psmail.xyz>"

RUN dnf install -y \
    glibc-langpack-cs \
    git \
    make \
    vim \
    packit \
    tmt \
    tig \
    glade \
    python3-pylint \
    python3-sphinx \
    python3-sphinx_rtd_theme \
    python3-wheel \
    shellcheck && \
    dnf builddep -y anaconda
