ARG fedora_version=34
FROM localhost/base:${fedora_version}

LABEL com.github.containers.toolbox="true" \
      usage="This image is meant to be used by toolbox -i <image-name> <container-name>" \
      summary="Image for publishing packages" \
      maintainer="Jiri Konecny <DragonLich@psmail.xyz>"

RUN dnf install -y \
    packit \
    fedpkg \
    twine \
    vim && \
    dnf builddep -y anaconda && \
    dnf clean all
