ARG fedora_version=36
FROM registry.fedoraproject.org/fedora-toolbox:${fedora_version}

LABEL com.github.containers.toolbox="true" \
      usage="This image is meant to be used by distrobox create -i <image-name> <container-name>" \
      summary="Base image used for other specialized images" \
      maintainer="Jiri Konecny <DragonLich@psmail.xyz>"

RUN dnf update -y && \
    dnf install -y 'dnf-command(copr)' && \
    dnf install -y \
# to be able to run commands on the host
    flatpak-spawn \
    fish \
# add terminfo packages for terminals which I'm testing
    foot-terminfo \
    pinentry-gnome3 \
    wl-clipboard \
    glibc-langpack-cs \
    glibc-langpack-en \
# distrobox dependencies
    bc \
    curl \
    diffutils \
    findutils \
    less \
    ncurses \
    passwd \
    pinentry \
    procps-ng \
    shadow-utils \
    sudo \
    util-linux \
    vte-profile \
    wget && \
# clean everything
    dnf clean all

# Enable flatpak applications in the container. Main reason is to be able open web sites in flatpak app.
RUN ln -s /usr/bin/distrobox-host-exec /usr/bin/flatpak
