FROM registry.fedoraproject.org/fedora-toolbox:34

LABEL com.github.containers.toolbox="true" \
      usage="This image is meant to be used by toolbox -i <image-name> <container-name>" \
      summary="Base image used for other specialized images" \
      maintainer="Jiri Konecny <DragonLich@psmail.xyz>"

RUN dnf install -y \
    fish \
    wl-clipboard && \
    dnf clean all