ARG fedora_version=34
FROM registry.fedoraproject.org/fedora-toolbox:${fedora_version}

LABEL com.github.containers.toolbox="true" \
      usage="This image is meant to be used by toolbox -i <image-name> <container-name>" \
      summary="Base image used for other specialized images" \
      maintainer="Jiri Konecny <DragonLich@psmail.xyz>"

RUN dnf update -y && \
    dnf copr enable -y atim/starship && \
    dnf install -y \
    fish \
# need to have the package installed so that container knows details about it
    foot-terminfo \
    starship \
    pinentry-gnome3 \
    wl-clipboard \
    glibc-langpack-cs \
    glibc-langpack-en && \
    dnf clean all
