FROM localhost/base:34

LABEL com.github.containers.toolbox="true" \
      usage="This image is meant to be used by toolbox -i <image-name> <container-name>" \
      summary="Image for my emacs" \
      maintainer="Jiri Konecny <DragonLich@psmail.xyz>"

# Required by emacs
#
# glibc-langpack-cs - missing locale
# google-noto-cjk-fonts-common  - add missing font for bottom modes indicators (Spacemacs)
#
# These are utilities used by emacs:
#
# ag - search engine (alternative to grep)
# pylint - python static linter
# discount - Markdown to HTML conventor
# importmagic|epc - to enable importmagic features
#
RUN dnf install -y \
    emacs \
    google-noto-cjk-fonts-common \
    glibc-langpack-cs \
    ag \
    python3-pylint \
    discount \
    python3-importmagic \
    python3-epc \
    git \
    make && \
    dnf clean all