FROM localhost/base:34

LABEL com.github.containers.toolbox="true" \
      usage="This image is meant to be used by toolbox -i <image-name> <container-name>" \
      summary="Image for transmission-remote tool" \
      maintainer="Jiri Konecny <DragonLich@psmail.xyz>"

RUN dnf install -y \
    transmission-remote-gtk
